version: "3"

services:
  moot:
    build: .
    restart: always
    ports:
      - 80:8000
    env_file: .env
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: moot
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
